#!/bin/bash

ismuted() {
  wpctl get-volume @DEFAULT_AUDIO_SINK@ | rg -i muted
  echo $?
}

# Get Volume
get_volume() {
	status=$(ismuted)

	if [[ "$status" == 1 ]]; then
		volume=`wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2*100}'`
		echo "$volume"
	else
		echo "Mute"
	fi
}

# Get icons
get_icon() {
	vol="$(get_volume)"
	current="${vol%%%}"
	status=$(ismuted)

	if [[ "$status" == 1 ]]; then
		if [[ "$current" -eq "0" ]]; then
			echo "ﱝ"
		elif [[ ("$current" -ge "0") && ("$current" -le "30") ]]; then
			echo "奄"
		elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
			echo "奔"
		elif [[ ("$current" -ge "60") && ("$current" -le "100") ]]; then
			echo "墳"
		fi
	else
		echo "ﱝ"
	fi
}

# Increase Volume
inc_volume() {
	wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
}

# Decrease Volume
dec_volume() {
	wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
}

# Toggle Mute
toggle_mute() {
	wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	get_volume
elif [[ "$1" == "--icon" ]]; then
	get_icon
elif [[ "$1" == "--ism" ]]; then
	ismuted
elif [[ "$1" == "--inc" ]]; then
	inc_volume
elif [[ "$1" == "--dec" ]]; then
	dec_volume
elif [[ "$1" == "--toggle" ]]; then
	toggle_mute
else
	get_volume
fi